/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#273647",
        "secondary": "#bfc7d8",
        "error-container": "#93000a",
        "background": "#051424",
        "on-primary-fixed-variant": "#5e4200",
        "primary": "#ffdca1",
        "surface-container-highest": "#273647",
        "secondary-fixed": "#dbe3f4",
        "on-tertiary-fixed-variant": "#3c475a",
        "on-tertiary-fixed": "#111c2d",
        "surface-container-high": "#1c2b3c",
        "primary-fixed": "#ffdea8",
        "on-error-container": "#ffdad6",
        "on-secondary": "#29313e",
        "inverse-surface": "#d4e4fa",
        "on-surface-variant": "#d5c4ab",
        "surface-container-low": "#0d1c2d",
        "on-tertiary-container": "#475265",
        "surface-dim": "#051424",
        "on-secondary-container": "#aeb5c6",
        "inverse-primary": "#7c5800",
        "on-background": "#d4e4fa",
        "on-primary-fixed": "#271900",
        "surface": "#051424",
        "surface-bright": "#2c3a4c",
        "outline-variant": "#514532",
        "on-error": "#690005",
        "surface-tint": "#ffba20",
        "on-surface": "#d4e4fa",
        "primary-container": "#ffb800",
        "error": "#ffb4ab",
        "inverse-on-surface": "#233143",
        "surface-container-lowest": "#010f1f",
        "tertiary": "#d6e1f9",
        "outline": "#9e8f78",
        "tertiary-fixed": "#d8e3fb",
        "tertiary-container": "#bac5dd",
        "secondary-fixed-dim": "#bfc7d8",
        "surface-container": "#122131",
        "on-tertiary": "#263143",
        "primary-fixed-dim": "#ffba20",
        "on-primary": "#412d00",
        "tertiary-fixed-dim": "#bcc7de",
        "on-secondary-fixed-variant": "#3f4755",
        "secondary-container": "#3f4755",
        "on-secondary-fixed": "#141c28",
        "on-primary-container": "#6b4c00"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "container-max": "1440px",
        "stack-xs": "4px",
        "stack-sm": "8px",
        "margin-mobile": "20px",
        "stack-lg": "32px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "stack-md": "16px",
        "stack-xl": "64px"
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["JetBrains Mono"],
        "headline-xl": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["13px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
