/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#000000",
        "surface": "#0a0a0a",
        "surface-container": "#0f0f0f",
        "surface-container-low": "#070707",
        "surface-container-high": "#151515",
        "surface-container-highest": "#1a1a1a",
        "surface-variant": "#1e1e1e",
        "surface-dim": "#000000",
        "surface-bright": "#2a2a2a",
        "surface-tint": "#e8a634",
        "on-surface": "#e8e8e8",
        "on-surface-variant": "rgba(255,255,255,0.62)",
        "on-background": "#e8e8e8",
        "primary": "#e8a634",
        "primary-container": "#e8a634",
        "primary-fixed": "#f0c060",
        "primary-fixed-dim": "#e8a634",
        "on-primary": "#000000",
        "on-primary-container": "#5e4200",
        "on-primary-fixed": "#271900",
        "on-primary-fixed-variant": "#5e4200",
        "inverse-primary": "#7c5800",
        "secondary": "#999999",
        "secondary-container": "#2a2a2a",
        "secondary-fixed": "#cccccc",
        "secondary-fixed-dim": "#999999",
        "on-secondary": "#1a1a1a",
        "on-secondary-container": "#aaaaaa",
        "on-secondary-fixed": "#111111",
        "on-secondary-fixed-variant": "#333333",
        "tertiary": "#bbbbbb",
        "tertiary-container": "#2a2a2a",
        "tertiary-fixed": "#dddddd",
        "tertiary-fixed-dim": "#bbbbbb",
        "on-tertiary": "#1a1a1a",
        "on-tertiary-container": "#666666",
        "on-tertiary-fixed": "#111111",
        "on-tertiary-fixed-variant": "#333333",
        "error": "#e84040",
        "error-container": "#3a1010",
        "on-error": "#ffffff",
        "on-error-container": "#ff8a8a",
        "outline": "rgba(255,255,255,0.22)",
        "outline-variant": "rgba(255,255,255,0.12)",
        "inverse-surface": "#e8e8e8",
        "inverse-on-surface": "#1a1a1a",
        "warning": "#e8a634",
        "success": "#34c759",
      },
      borderRadius: {
        DEFAULT: "0px",
        sm: "2px",
        md: "4px",
        lg: "6px",
        xl: "8px",
        "2xl": "12px",
        "3xl": "16px",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "stack-xs": "4px",
        "stack-sm": "8px",
        "margin-mobile": "20px",
        "stack-lg": "32px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "stack-md": "16px",
        "stack-xl": "64px",
        "unit": "6px",
        "container-margin": "20px",
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["JetBrains Mono"],
        "headline-xl": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["13px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
